/**
 * Her stadyum SVG dosyasında `data-select` içinde geçen benzersiz `zone:` değerleri.
 * İlan kategorisi (bloksuz eşleşme) ve `STADIUM_CATEGORY_THEMES` anahtarları bu isimlerle uyumlu olmalı;
 * eşleşme `normalizeStadiumZoneKey` ile yapılır.
 *
 * Yenilemek: `node scripts/extract-stadium-zones.mjs`
 */

export const STADIUM_ZONE_KEYS: Record<string, readonly string[]> = {
  "ali-samiyen": [
    "100",
    "101",
    "101v",
    "102",
    "103",
    "104",
    "105",
    "106",
    "107",
    "108",
    "109",
    "110",
    "111",
    "112",
    "113",
    "114",
    "115",
    "116",
    "117",
    "118",
    "119",
    "120",
    "121",
    "122",
    "123",
    "124",
    "125",
    "125v",
    "201",
    "202",
    "203",
    "204",
    "205",
    "206",
    "207",
    "208",
    "209",
    "210",
    "211",
    "212",
    "213",
    "214",
    "215",
    "216",
    "217",
    "218",
    "219",
    "220",
    "221",
    "222",
    "223",
    "224",
    "225",
    "304",
    "305",
    "306",
    "307",
    "308",
    "309",
    "400",
    "401",
    "402",
    "403",
    "404",
    "405",
    "406",
    "407",
    "408",
    "409",
    "410",
    "411",
    "412",
    "413",
    "414",
    "415",
    "416",
    "417",
    "418",
    "419",
    "420",
    "421",
    "422",
    "423",
    "424",
    "425",
    "426",
    "427",
    "428",
    "429",
    "Alt Kat",
    "Alt Kat Kenar",
    "Kale Arkası Alt Kat",
    "Kale Arkası Üst Kat",
    "Loca",
    "Misafir",
    "Üst Kat",
    "VIP",
  ],
  "ataturk-olimpiyat-stadyumu": [
    "200",
    "2011",
    "2021",
    "2031",
    "2041",
    "2051",
    "2061",
    "2071",
    "2081",
    "209",
    "210",
    "211",
    "301",
    "302",
    "311",
    "312",
    "313",
    "314",
    "315",
    "316",
    "317",
    "318",
    "319",
    "320",
    "321",
    "322",
    "323",
    "324",
    "334",
    "335",
    "336",
    "401",
    "402",
    "403",
    "404",
    "405",
    "4054",
    "406",
    "601",
    "602",
    "605",
    "606",
    "701",
    "702",
    "703",
    "704",
    "705",
    "706",
    "707",
    "707-706",
    "708",
    "709",
    "709-708",
    "710",
    "711",
    "712",
    "713",
    "714",
    "715",
    "716",
    "717",
    "718",
    "7181_",
    "719",
    "719-720",
    "720",
    "721",
    "722",
    "901",
    "902",
    "903",
    "904",
    "905",
    "906",
    "907",
    "908",
    "909",
    "910",
    "911",
    "912",
    "913",
    "914",
    "Batı Tribün",
    "Category 2",
    "Doğu Tribün",
    "VIP",
  ],
  "basaksehir-fatih-terim-stadyumu": [
    "Batı A",
    "Batı A1",
    "Batı Alt Kat",
    "Batı B",
    "Batı B1",
    "Batı C",
    "Batı C1",
    "Batı D",
    "Batı D1",
    "Batı E",
    "Batı E1",
    "Batı F",
    "Batı F1",
    "Batı G",
    "Batı G1",
    "Batı Üst Kat",
    "Doğu A",
    "Doğu A1",
    "Doğu Alt Kat",
    "Doğu B",
    "Doğu B1",
    "Doğu C",
    "Doğu C1",
    "Doğu D",
    "Doğu D1",
    "Doğu E",
    "Doğu E1",
    "Doğu F",
    "Doğu F1",
    "Doğu G",
    "Doğu G1",
    "Doğu Üst Kat",
    "Güney Alt Kat",
    "Güney Üst Kat",
    "Kale Arkası A",
    "Kale Arkası A1",
    "Kale Arkası B",
    "Kale Arkası B1",
    "Kale Arkası B2",
    "Kale Arkası B3",
    "Kale Arkası C",
    "Kale Arkası C1",
    "Kale Arkası C2",
    "Kale Arkası C3",
    "Kale Arkası D",
    "Kale Arkası D1",
    "Kale Arkası D2",
    "Kale Arkası D3",
    "Kale Arkası E",
    "Kale Arkası E1",
    "Kale Arkası E2",
    "Kale Arkası E3",
    "Kuzey Alt Kat",
    "Kuzey Üst Kat",
    "Misafir",
  ],
  "caykur-didi-stadyumu": [
    "A10",
    "A7",
    "A8",
    "A9",
    "B6",
    "B7",
    "B8",
    "B9",
    "C4",
    "C5",
    "C6",
    "C7",
    "D4",
    "D5",
    "D6",
    "D7",
    "E3",
    "E4",
    "E5",
    "E6",
    "F1",
    "F2",
    "F3",
    "F4",
    "G1",
    "G2",
    "Güney Tribün",
    "H1",
    "H2",
    "I1",
    "J",
    "J1",
    "K",
    "K1",
    "Kuzey Tribün",
    "L",
    "L1",
    "M",
    "M1",
    "Misafir",
    "N",
    "O",
    "O1",
    "P",
    "P1",
    "R",
    "R1",
    "S",
    "S1",
    "Yan Tribün",
  ],
  "coredon-airlines-park-antalya-stadyumu": [
    "Basın",
    "Batı Alt",
    "Batı Alt A",
    "Batı Alt B",
    "Batı Alt C",
    "Batı Alt D",
    "Batı Alt E",
    "Batı Alt F",
    "Batı Alt G",
    "Batı Localar",
    "Batı Üst",
    "Batı Üst A",
    "Batı Üst C",
    "Batı Üst D",
    "Batı Üst E",
    "Batı Üst F",
    "Doğu Alt",
    "Doğu Alt A",
    "Doğu Alt B",
    "Doğu Alt C",
    "Doğu Alt D",
    "Doğu Alt E",
    "Doğu Alt F",
    "Doğu Alt G",
    "Doğu Localar",
    "Doğu Üst",
    "Doğu Üst A",
    "Doğu Üst B",
    "Doğu Üst C",
    "Doğu Üst D",
    "Doğu Üst E",
    "Doğu Üst F",
    "Doğu Üst G",
    "Güney",
    "Kale Arkası A",
    "Kale Arkası A1",
    "Kale Arkası A2",
    "Kale Arkası A3",
    "Kale Arkası B",
    "Kale Arkası B1",
    "Kale Arkası B2",
    "Kale Arkası B3",
    "Kale Arkası C",
    "Kale Arkası C1",
    "Kale Arkası C2",
    "Kale Arkası C3",
    "Kale Arkası C4",
    "Kale Arkası C5",
    "Kale Arkası C6",
    "Kale Arkası C7",
    "Kale Arkası D",
    "Kale Arkası D1",
    "Kale Arkası D2",
    "Kale Arkası D3",
    "Kale Arkası D4",
    "Kale Arkası D5",
    "Kale Arkası D6",
    "Kale Arkası D7",
    "Kale Arkası E",
    "Kale Arkası E1",
    "Kale Arkası E2",
    "Kale Arkası E3",
    "Kale Arkası E4",
    "Kale Arkası E5",
    "Kale Arkası E6",
    "Kale Arkası E7",
    "Kuzey",
    "Misafir A",
    "Misafir A2",
    "Misafir A3",
    "Misafir B",
    "Misafir B1",
    "Misafir B2",
    "Misafir B3",
    "Misafir Tribün",
    "Misafir-A1",
    "MPA",
    "MPB",
    "MPC",
    "Protokol",
  ],
  "eryaman-stadyumu": [
    "BOŞ",
    "Güney A",
    "Güney B",
    "Güney C",
    "Güney D",
    "Güney E",
    "Güney Kale Arkası",
    "Kapalı A",
    "Kapalı A1",
    "Kapalı B",
    "Kapalı B1",
    "Kapalı C",
    "Kapalı C1",
    "Kapalı D",
    "Kapalı D1",
    "Kapalı E",
    "Kapalı E1",
    "Kapalı F",
    "Kapalı F1",
    "Kapalı G",
    "Kapalı H",
    "Kapalı Sol A1",
    "Kapalı Sol B1",
    "Kapalı Sol C1",
    "Kapalı Sol D1",
    "Kapalı Tribün",
    "Kuzey A",
    "Kuzey B",
    "Kuzey C",
    "Kuzey E",
    "Kuzey Kale Arkası",
    "KuzeyD",
    "Maraton A",
    "Maraton A1",
    "Maraton B",
    "Maraton B1",
    "Maraton C",
    "Maraton C1",
    "Maraton D",
    "Maraton D1",
    "Maraton E",
    "Maraton E1",
    "Maraton F",
    "Maraton F1",
    "Maraton G",
    "Maraton G1",
    "Maraton H",
    "Maraton H1",
    "Maraton Tribün",
    "Misafir",
  ],
  "festival-park-yenikapi": [
    "Genel",
    "General",
    "Ön Sahne",
    "Sahne Onu",
    "VIP",
    "Vip Teras",
  ],
  "gain-park-stadyumu": [
    "A",
    "A1",
    "A2_",
    "A3_",
    "A4_",
    "A5_",
    "A6_",
    "B",
    "B1",
    "B2_",
    "B3_",
    "B4_",
    "B5_",
    "C",
    "C1_",
    "C2_",
    "C3_",
    "D",
    "D1_",
    "D2_",
    "D3_",
    "E",
    "E1_",
    "E2_",
    "F",
    "G",
    "Güney Kale Arkası Tribün",
    "H",
    "I",
    "Kapalı Tribün",
    "KC",
    "KC1_",
    "KC2_",
    "Kuzey Kale Arkası Tribün",
    "Maraton Tribün",
    "Misafir",
  ],
  "gaziantep-buyuksehir-stadyumu": [
    "Basın",
    "Güney A Alt",
    "Güney A Üst",
    "Güney B Alt",
    "Güney B Üst",
    "Güney C Alt",
    "Güney C Üst",
    "Güney D Alt",
    "Güney D Üst",
    "Güney E Alt",
    "Güney E Üst",
    "Güney F Alt",
    "Güney F Üst",
    "Güney G Alt",
    "Güney G Üst",
    "Güney H Alt",
    "Güney H Üst",
    "Güney J Üst",
    "Güney Kale Arkası",
    "Kuzey A Alt",
    "Kuzey A Üst",
    "Kuzey B Alt",
    "Kuzey B Üst",
    "Kuzey C Alt",
    "Kuzey C Üst",
    "Kuzey D Alt",
    "Kuzey D Üst",
    "Kuzey E Alt",
    "Kuzey E Üst",
    "Kuzey F Alt",
    "Kuzey F Üst",
    "Kuzey G Alt",
    "Kuzey H Alt",
    "Kuzey Kale Arkası",
    "Maraton A Alt",
    "Maraton A Üst",
    "Maraton B Alt",
    "Maraton B Üst",
    "Maraton C Alt",
    "Maraton C Üst",
    "Maraton D Alt",
    "Maraton D Üst",
    "Maraton E Alt",
    "Maraton E Üst",
    "Maraton F Alt",
    "Maraton F Üst",
    "Maraton G Alt",
    "Maraton G Üst",
    "Maraton H Alt",
    "Maraton I Alt",
    "Maraton Tribün",
    "Misafir",
    "Protokol",
    "VIP",
    "Vip A Alt",
    "Vip A Üst",
    "Vip B Alt",
    "Vip B Üst",
    "Vip C Alt",
    "Vip C Üst",
    "Vip D Alt",
    "Vip D Üst",
    "Vip E Alt",
    "Vip F Alt",
    "Vip G Alt",
    "Vip H Alt",
    "Vip I Alt",
    "Vip K Üst",
  ],
  "gursel-aksel-stadyumu": [
    "200",
    "201",
    "202",
    "203",
    "204",
    "205",
    "206",
    "207",
    "208",
    "209",
    "210",
    "211",
    "212",
    "213",
    "214",
    "215",
    "216",
    "217",
    "218",
    "219",
    "220",
    "221",
    "222",
    "223",
    "224",
    "225",
    "Batı Tribün",
    "Doğu Tribün",
    "Güney Tribün",
    "Kuzey Tribün",
    "Misafir",
    "VIP",
    "West Side",
  ],
  "harbiye-cemil-topuzlu": [
    "1. Kategori",
    "3. Kategori",
    "4. Kategori",
    "5. Kategori",
    "6. Kategori",
    "A BLOK",
    "B BLOK",
    "C BLOK",
    "C SAĞ BLOK",
    "C SOL BLOK",
    "D BLOK",
    "E BLOK",
    "F BLOK",
    "G BLOK",
    "H BLOK",
    "K BLOK",
    "L BLOK",
    "M BLOK",
    "N BLOK",
    "ÖN LOCA",
    "P BLOK",
    "SAHNE ÖNÜ",
  ],
  "konya-medas-stadyumu": [
    "Alt Kat A",
    "Alt Kat A1",
    "Alt Kat B",
    "Alt Kat B1",
    "Alt Kat C",
    "Alt Kat C1",
    "Alt Kat D",
    "Alt Kat D1",
    "Alt Kat E",
    "Alt Kat E1",
    "Alt Kat F",
    "Alt Kat F1",
    "Alt Kat G",
    "Alt Kat G1",
    "Batı Tribün",
    "Doğu Tribün",
    "Güney Tribün",
    "Kale Arkası A",
    "Kale Arkası A1",
    "Kale Arkası A2",
    "Kale Arkası B",
    "Kale Arkası B1",
    "Kale Arkası B2",
    "Kale Arkası C",
    "Kale Arkası C1",
    "Kale Arkası C2",
    "Kale Arkası D",
    "Kale Arkası D1",
    "Kale Arkası D2",
    "Kale Arkası D3",
    "Kale Arkası E",
    "Kale Arkası E1",
    "Kale Arkası E2",
    "Kale Arkası E3",
    "Kale Arkası F",
    "Kale Arkası F1",
    "Kale Arkası F2",
    "Kale Arkası F3",
    "Kale Arkası G2",
    "Kale Arkası G3",
    "Kale Arkası H2",
    "Kale Arkası J2",
    "Kale Arkası J3",
    "Kale Arkası K2",
    "Kale Arkası K3",
    "Kuzey Tribün",
    "Kuzey Tribün H3",
    "Misafir Tribün",
    "Misafir Tribün A",
    "Misafir Tribün B",
    "Misafir Tribün C",
    "Üst Kat A",
    "Üst Kat A1",
    "Üst Kat B",
    "Üst Kat B1",
    "Üst Kat C",
    "Üst Kat C1",
    "Üst Kat D",
    "Üst Kat D1",
    "Üst Kat E",
    "Üst Kat F",
    "Üst Kat G",
    "VIP",
  ],
  "recep-tayyip-erdogan-stadyumu": [
    "A Blok",
    "Açık Tribün",
    "B Blok",
    "C Blok",
    "D Blok",
    "E Blok",
    "F Blok",
    "Kale Arkası",
    "Kale Arkası A",
    "Kale Arkası B",
    "Kapalı Tribün",
    "Misafir",
    "Misafir Tribün",
    "VIP",
    "VIPUST",
  ],
  "rhg-enerturk-enerji-stadyumu": [
    "BOŞ",
    "Güney A",
    "Güney B",
    "Güney C",
    "Güney D",
    "Güney E",
    "Güney Kale Arkası",
    "Kapalı A",
    "Kapalı A1",
    "Kapalı B",
    "Kapalı B1",
    "Kapalı C",
    "Kapalı C1",
    "Kapalı D",
    "Kapalı D1",
    "Kapalı E",
    "Kapalı E1",
    "Kapalı F",
    "Kapalı F1",
    "Kapalı G",
    "Kapalı H",
    "Kapalı Sağ C",
    "Kapalı Tribün",
    "Kuzey A",
    "Kuzey B",
    "Kuzey C",
    "Kuzey D",
    "Kuzey E",
    "Kuzey Tribün",
    "Maraton A",
    "Maraton A1",
    "Maraton B",
    "Maraton B1",
    "Maraton C1",
    "Maraton D",
    "Maraton D1",
    "Maraton E",
    "Maraton E1",
    "Maraton F",
    "Maraton F1",
    "Maraton G",
    "Maraton G1",
    "Maraton H",
    "Maraton H1",
    "Maraton Tribün",
    "MaratonC",
    "Misafir",
  ],
  "samsun-19-mayis-stadyumu": [
    "Alt Kat A",
    "Alt Kat A1",
    "Alt Kat B",
    "Alt Kat B1",
    "Alt Kat C1",
    "Alt Kat D",
    "Alt Kat D1",
    "Alt Kat E",
    "Alt Kat E1",
    "Alt Kat F",
    "Alt Kat F1",
    "Alt Kat G",
    "Alt Kat G1",
    "AltKat__-_C",
    "Batı Tribün",
    "Doğu Tribün",
    "Güney Tribün",
    "Kale Arkası A",
    "Kale Arkası A1",
    "Kale Arkası A2",
    "Kale Arkası B",
    "Kale Arkası B1",
    "Kale Arkası B2",
    "Kale Arkası C",
    "Kale Arkası C1",
    "Kale Arkası C2",
    "Kale Arkası D",
    "Kale Arkası D1",
    "Kale Arkası D2",
    "Kale Arkası D3",
    "Kale Arkası E",
    "Kale Arkası E1",
    "Kale Arkası E2",
    "Kale Arkası E3",
    "Kale Arkası F",
    "Kale Arkası F1",
    "Kale Arkası F2",
    "Kale Arkası F3",
    "Kale Arkası G2",
    "Kale Arkası G3",
    "Kale Arkası H2",
    "Kale Arkası J2",
    "Kale Arkası J3",
    "Kale Arkası K2",
    "Kale Arkası K3",
    "Kuzey Tribün",
    "Kuzey Tribün H3",
    "Misafir",
    "Misafir A",
    "Misafir B",
    "Misafir C",
    "Protokol",
    "Üst Kat A",
    "Üst Kat A1",
    "Üst Kat B1",
    "Üst Kat C",
    "Üst Kat C1",
    "Üst Kat D",
    "Üst Kat D1",
    "Üst Kat E",
    "Üst Kat F",
    "Üst Kat G",
    "ÜstKat_-_B",
  ],
  "senol-gunes-spor-kompleksi": [
    "Batı A",
    "Batı B",
    "Batı C",
    "Batı D",
    "Batı E",
    "Batı F",
    "Batı G",
    "Batı H",
    "Batı I",
    "Batı J",
    "Batı Tribün",
    "Doğu A",
    "Doğu B",
    "Doğu C",
    "Doğu D",
    "Doğu E",
    "Doğu F",
    "Doğu G",
    "Doğu H",
    "Doğu I",
    "Doğu J",
    "Doğu K",
    "Doğu L",
    "Doğu Tribün",
    "Güney A",
    "Güney B",
    "Güney C",
    "Güney D",
    "Güney E",
    "Güney F",
    "Güney G",
    "Güney H",
    "Güney I",
    "Güney J",
    "Güney K",
    "Güney L",
    "Güney Tribün",
    "Kuzey A",
    "Kuzey B",
    "Kuzey C",
    "Kuzey D",
    "Kuzey E",
    "Kuzey H",
    "Kuzey I",
    "Kuzey J",
    "Kuzey K",
    "Kuzey L",
    "Kuzey Tribün",
    "Misafir F",
    "Misafir G",
    "Misafir Tribün",
    "VIP",
    "Vip Gold A",
    "Vip Gold B",
    "Vip Platinum A",
    "Vip Platinum B",
    "Vip Silver A",
    "Vip Silver B",
    "VipPlatinum_C",
  ],
  "sukru-saracoglu": [
    "1907",
    "1907-A",
    "1907-B",
    "1907-C",
    "1907-D",
    "1907-E",
    "1907-F",
    "1907-G",
    "1907-H",
    "1907-I",
    "1907-J",
    "1907-K",
    "1907-L",
    "1907-M",
    "1907-N",
    "AK-C",
    "AK-C1",
    "AK-D",
    "AK-D1",
    "AK-E",
    "AK-E1",
    "AK-F",
    "AK-F1",
    "AK-G",
    "AK-G1",
    "Alt Kat",
    "Fenerium Üst A1",
    "Fenerium Üst B1",
    "Fenerium Üst C1",
    "Fenerium Üst D1",
    "Fenerium Üst E1",
    "Fenerium Üst F1",
    "Fenerium Üst G1",
    "Fenerium Üst H1",
    "Fenerium Üst I1",
    "Kale Arkası Kuzey",
    "Kale Arkası Spor Toto",
    "Kenar",
    "Kenar-A",
    "Kenar-A1",
    "Kenar-B",
    "Kenar-B1",
    "Kenar-H",
    "Kenar-H1",
    "Kenar-I",
    "Kenar-I1",
    "Kuzey A",
    "Kuzey B",
    "Kuzey C",
    "Kuzey D",
    "Kuzey E",
    "Kuzey F",
    "Kuzey I",
    "Kuzey J",
    "Kuzey K",
    "Kuzey L",
    "Kuzey M",
    "Kuzey N",
    "Maraton Üst A",
    "Maraton Üst B",
    "Maraton Üst C",
    "Maraton Üst D",
    "Maraton Üst E",
    "Maraton Üst F",
    "Maraton Üst G",
    "Maraton Üst H",
    "Maraton Üst I",
    "Misafir",
    "Misafir-F",
    "Misafir-G",
    "Misafir-H",
    "Misafir-N",
    "Misafir-O",
    "Misafir-P",
    "OKUL-A1",
    "OKUL-B1",
    "OKUL-C1",
    "OKUL-D1",
    "OKUL-E1",
    "OKUL-F1",
    "OKUL-G1",
    "OKUL-H1",
    "OKUL-I1",
    "OKUL-J1",
    "OKUL-K1",
    "OKUL-L1",
    "OKUL-M1",
    "OKUL-N1",
    "OKUL-O1",
    "OKUL-P1",
    "Üst Kat",
    "Üst Kenar",
  ],
  "tupras-stadyumu": [
    "102",
    "103",
    "104",
    "105",
    "106",
    "107",
    "108",
    "109",
    "110",
    "111",
    "112",
    "113",
    "114",
    "115",
    "116",
    "117",
    "118",
    "119",
    "120",
    "121",
    "122",
    "123",
    "124",
    "125",
    "1903 Tribünü",
    "401",
    "402",
    "403",
    "404",
    "405",
    "406",
    "407",
    "408",
    "409",
    "410",
    "411",
    "412",
    "413",
    "414",
    "415",
    "416",
    "417",
    "418",
    "419",
    "420",
    "421",
    "422",
    "423",
    "424",
    "425",
    "426",
    "427",
    "428",
    "429",
    "430",
    "A",
    "Alt Kat",
    "B",
    "C",
    "D",
    "E",
    "Kale Arkası Alt Kat",
    "Kale Arkası Üst Kat",
    "Kenar",
    "Misafir",
    "Üst Kat",
    "VIP",
  ],
  "yildiz-entegre-kocaeli-stadyumu": [
    "101",
    "102",
    "103",
    "111",
    "112",
    "113",
    "114",
    "115",
    "116",
    "124",
    "125",
    "126",
    "204",
    "205",
    "206",
    "207",
    "208",
    "209",
    "210",
    "217",
    "218",
    "219",
    "220",
    "221",
    "222",
    "223",
    "301",
    "302",
    "303",
    "304",
    "305",
    "306",
    "307",
    "308",
    "309",
    "310",
    "311",
    "312",
    "313",
    "314",
    "315",
    "316",
    "317",
    "318",
    "319",
    "320",
    "321",
    "322",
    "323",
    "324",
    "325",
    "326",
    "327",
    "Batı Tribünü",
    "Doğu Tribünü",
    "Kale Arkası",
    "Misafir",
    "Protocol",
    "PROTOKOL",
  ],
} as const;

export type StadiumZoneCatalogSlug = keyof typeof STADIUM_ZONE_KEYS;
